development:
  adapter: postgresql
  encoding: unicode
  database: g_development
  host: localhost
  username: rails
  password: root
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: g_test
  host: localhost
  username: rails
  password: root
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: g_production
  host: localhost
  username: rails
  password: root
  pool: 5
